apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secret-rotation
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: my-secrets
    type: Opaque
    data:
    - objectName: TEXT1
      key: TEXT1
    - objectName: TEXT2
      key: TEXT2
    - objectName: COMPANY
      key: COMPANY               # Kubernetes secret key name
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<Managed identity client ID>"
    keyvaultName: "cy-key-vault-demo"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: TEXT1                   # Key vault secret name
          objectType: secret                  # The object type is secret
        - |
          objectName: TEXT2                 
          objectType: secret 
        - |
          objectName: COMPANY                 
          objectType: secret 
    tenantId: "<Your Azure Tenant ID">
    # This enables syncing the secret from Key Vault to a Kubernetes secret
    syncSecret.enabled: "true"
